version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/opt
    ports:
    - "6543:6543"
    network_mode: host
    command: [
      "python",
      "app.py",
    ]
